#!/usr/bin/env python3
from __future__ import annotations

import argparse
import datetime as dt
from email.utils import format_datetime
from html import escape, unescape
from pathlib import Path
import re

import feedparser

HEADING_PATTERN = re.compile(r"(?is)<h(?P<level>[1-6])[^>]*>(?P<content>.*?)</h(?P=level)>")
TAG_PATTERN = re.compile(r"(?is)<[^>]+>")
BREAK_PATTERN = re.compile(r"(?i)<br\s*/?>")
BLOCK_END_PATTERN = re.compile(r"(?i)</(p|div|li|ul|ol|blockquote|section|article|h[1-6])>")


def load_feed_urls(path: Path) -> list[str]:
    urls: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        urls.append(line)
    return urls


def parse_entry_date(entry: dict) -> dt.datetime:
    for key in ("published_parsed", "updated_parsed"):
        value = entry.get(key)
        if value:
            return dt.datetime(*value[:6], tzinfo=dt.timezone.utc)
    return dt.datetime.now(dt.timezone.utc)


def html_to_text(value: str) -> str:
    text = unescape(value or "")
    text = BREAK_PATTERN.sub("\n", text)
    text = BLOCK_END_PATTERN.sub("\n", text)
    text = TAG_PATTERN.sub("", text)
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    lines = [line.strip() for line in text.split("\n")]
    text = "\n".join(line for line in lines if line)
    # Keep at most one empty line between blocks for plain-text readers.
    text = re.sub(r"\n{2,}", "\n\n", text)
    return text.strip()


def heading_from_html(value: str) -> str:
    match = HEADING_PATTERN.search(value or "")
    if not match:
        return ""
    return html_to_text(match.group("content"))


def without_first_heading(value: str) -> str:
    """Remove the first heading element from HTML and return the modified content."""
    return HEADING_PATTERN.sub("", value or "", count=1)


def aggregate_entries(urls: list[str]) -> list[dict]:
    entries: list[dict] = []
    for url in urls:
        parsed = feedparser.parse(url)
        for entry in parsed.entries:
            raw_title = entry.get("title") or ""
            link = entry.get("link") or url
            raw_summary = entry.get("summary") or entry.get("description") or ""
            heading_title = heading_from_html(raw_summary)
            title = heading_title or html_to_text(raw_title) or "Untitled"
            summary = html_to_text(without_first_heading(raw_summary))
            published = parse_entry_date(entry)
            source = html_to_text(parsed.feed.get("title") or "") or url
            entries.append(
                {
                    "title": title,
                    "link": link,
                    "summary": summary,
                    "published": published,
                    "source": source,
                }
            )

    entries.sort(key=lambda item: item["published"], reverse=True)
    return entries


def build_rss(entries: list[dict], channel_title: str = "RSSRelay Combined Feed") -> str:
    now = dt.datetime.now(dt.timezone.utc)
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<rss version=\"2.0\">",
        "  <channel>",
        f"    <title>{escape(channel_title)}</title>",
        "    <link>https://github.com/TV46/RSSRelay</link>",
        "    <description>A combined RSS feed generated by RSSRelay.</description>",
        f"    <lastBuildDate>{format_datetime(now)}</lastBuildDate>",
    ]

    for entry in entries:
        description = entry["summary"]
        source_line = f"Source: {entry['source']}" if entry["source"] else ""
        if description and source_line:
            description = f"{description}\n\n{source_line}"
        elif source_line:
            description = source_line

        lines.extend(
            [
                "    <item>",
                f"      <title>{escape(entry['title'])}</title>",
                f"      <link>{escape(entry['link'])}</link>",
                f"      <description>{escape(description)}</description>",
                f"      <pubDate>{format_datetime(entry['published'])}</pubDate>",
                "    </item>",
            ]
        )

    lines.extend(["  </channel>", "</rss>"])
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Combine multiple RSS feeds into one output feed.")
    parser.add_argument("--feeds-file", default="feeds.txt", help="Path to file containing feed URLs")
    parser.add_argument("--output", default="feed.rss", help="Output RSS file path")
    args = parser.parse_args()

    feeds_file = Path(args.feeds_file)
    output_file = Path(args.output)

    urls = load_feed_urls(feeds_file)
    entries = aggregate_entries(urls)
    output_file.write_text(build_rss(entries), encoding="utf-8")
    print(f"Wrote {len(entries)} entries to {output_file}")


if __name__ == "__main__":
    main()
