#!/usr/bin/env python3
from __future__ import annotations

import argparse
import datetime as dt
from email.utils import format_datetime
from html import escape
from pathlib import Path

import feedparser


def load_feed_urls(path: Path) -> list[str]:
    urls: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        urls.append(line)
    return urls


def parse_entry_date(entry: dict) -> dt.datetime:
    for key in ("published_parsed", "updated_parsed"):
        value = entry.get(key)
        if value:
            return dt.datetime(*value[:6], tzinfo=dt.timezone.utc)
    return dt.datetime.now(dt.timezone.utc)


def aggregate_entries(urls: list[str]) -> list[dict]:
    entries: list[dict] = []
    for url in urls:
        parsed = feedparser.parse(url)
        for entry in parsed.entries:
            title = entry.get("title") or "Untitled"
            link = entry.get("link") or url
            summary = entry.get("summary") or entry.get("description") or ""
            published = parse_entry_date(entry)
            source = parsed.feed.get("title") or url
            entries.append(
                {
                    "title": title,
                    "link": link,
                    "summary": summary,
                    "published": published,
                    "source": source,
                }
            )

    entries.sort(key=lambda item: item["published"], reverse=True)
    return entries


def build_rss(entries: list[dict], channel_title: str = "RSSRelay Combined Feed") -> str:
    now = dt.datetime.now(dt.timezone.utc)
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<rss version=\"2.0\">",
        "  <channel>",
        f"    <title>{escape(channel_title)}</title>",
        "    <link>https://github.com/TV46/RSSRelay</link>",
        "    <description>A combined RSS feed generated by RSSRelay.</description>",
        f"    <lastBuildDate>{format_datetime(now)}</lastBuildDate>",
    ]

    for entry in entries:
        lines.extend(
            [
                "    <item>",
                f"      <title>{escape(entry['title'])}</title>",
                f"      <link>{escape(entry['link'])}</link>",
                f"      <description><![CDATA[{entry['summary']}<br/><br/>Source: {escape(entry['source'])}]]></description>",
                f"      <pubDate>{format_datetime(entry['published'])}</pubDate>",
                "    </item>",
            ]
        )

    lines.extend(["  </channel>", "</rss>"])
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Combine multiple RSS feeds into one output feed.")
    parser.add_argument("--feeds-file", default="feeds.txt", help="Path to file containing feed URLs")
    parser.add_argument("--output", default="feed.rss", help="Output RSS file path")
    args = parser.parse_args()

    feeds_file = Path(args.feeds_file)
    output_file = Path(args.output)

    urls = load_feed_urls(feeds_file)
    entries = aggregate_entries(urls)
    output_file.write_text(build_rss(entries), encoding="utf-8")
    print(f"Wrote {len(entries)} entries to {output_file}")


if __name__ == "__main__":
    main()
